name: 自动生成sidebar.md和git提交推送

on:
  push:
    paths:
      - 'docs/**/*.md'
      - 'docs/*.md'
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-sidebar:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 运行脚本生成 _sidebar.md
        run: python3  gen_docs_sidebar_md.py

      - name: 提交变更
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/_sidebar.md
          if git diff --cached --quiet; then
            echo "没有变更，跳过提交"
          else
            git commit -m "ci: 自动更新 _sidebar.md"
            git push
          fi
